"""Jev's vocabulary: the words it was born knowing, and the ones it must never learn.

``vocab_en.txt`` is English by frequency, generated by
``scripts/build_jev_vocab.py`` (see there for sources). Jev starts with only
the first ``WriterConfig.vocab_size`` of them; everything else it says, it
learned from the chat (see lexicon.py).
"""

from __future__ import annotations

from functools import cache
from pathlib import Path

VOCAB_FILE = Path(__file__).with_name("vocab_en.txt")

# Words Jev can neither be born with nor learn, however often it hears them.
# wordfreq's top lists already drop slurs; this covers the rest of what should
# never come out of a dice roll or be echoed into other conversations.
BLOCKED = frozenset(
    {
        "rape",
        "raped",
        "rapes",
        "raping",
        "rapist",
        "retard",
        "retarded",
        "negro",
        "nigger",
        "nigga",
        "niggas",
        "cunt",
        "whore",
        "slut",
        "tranny",
        "trannies",
        "fag",
        "fags",
        "faggot",
        "faggots",
        "kike",
        "spic",
        "chink",
        "gook",
        "wetback",
        "coon",
        "dyke",
    }
)


@cache
def load_vocab(path: Path = VOCAB_FILE) -> tuple[str, ...]:
    """Every word in the file, most frequent first (comment lines skipped)."""
    lines = path.read_text(encoding="utf-8").splitlines()
    return tuple(w for w in (line.strip() for line in lines) if w and not w.startswith("#"))
