"""Jev's vocabulary: the words it can pick from when nobody in the chat said them first.

``vocab_en.txt`` is English by frequency, generated by
``scripts/build_jev_vocab.py`` (see there for sources and exclusions).
"""

from __future__ import annotations

from functools import cache
from pathlib import Path

VOCAB_FILE = Path(__file__).with_name("vocab_en.txt")


@cache
def load_vocab(path: Path = VOCAB_FILE) -> tuple[str, ...]:
    """Every word in the file, most frequent first (comment lines skipped)."""
    lines = path.read_text(encoding="utf-8").splitlines()
    return tuple(w for w in (line.strip() for line in lines) if w and not w.startswith("#"))
